[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://test.sofi-assistant.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Кэширование: HTML всегда свежий, ассеты с хешами — длительный кэш
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
